auth:
  default: jwt
  drivers:
    jwt:
      algorithm: HS256
      secret: demopass
      refresh_ttl: 1209600 # 2 weeks, in seconds
      ttl: 7200 # 2 hours, in seconds
    oauth2:
      clientId: demoapp
      clientSecret: demopass
      redirectUri: %base_url%
      urlAuthorize: http://brentertainment.com/oauth2/lockdin/authorize
      urlAccessToken: http://brentertainment.com/oauth2/lockdin/token
      urlResourceOwnerDetails: http://brentertainment.com/oauth2/lockdin/resource
